name: MLflow CI

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install pandas
          pip install scikit-learn
          pip install matplotlib
          pip install mlflow
          pip install joblib

      - name: Run Training
        run: |
          cd MLProject
          python modelling.py

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: telco-churn-model
          path: |
            MLProject/model.pkl
            MLProject/metrics.json